version: '3'
services:
  chiguirongos-pg:
    image: postgres:14
    container_name: chiguirongos-pg
    privileged: true
    environment:
        - POSTGRES_DB=chig-calendario
        - POSTGRES_USER=chiguire
        - POSTGRES_PASSWORD=chiguirongos
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chiguire -d chig-calendario"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 30s

  chiguirongos-back:
    container_name: chiguirongos-back
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    depends_on:
      chiguirongos-pg:
        condition: service_healthy
    restart: on-failure 
    ports:
      - 8080:8080
    environment:
      - REPORT_FOLDER=./reports_tmp

  chiguirongos-front:
    container_name: chiguirongos-front
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    depends_on:
      - chiguirongos-pg
      - chiguirongos-back
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - 3000:3000
